Intevel/nuxt-directus

docs/content/en/usage/useDirectusFiles.md, docs/content/en/usage/useDirectusItems.md, playground/app.vue, src/runtime/composables/useDirectusAuth.ts, src/runtime/composables/useDirectusFiles.ts, src/runtime/composables/useDirectusItems.ts, src/runtime/types/index.d.ts
remove some missing typescript types
add typescript generics to the useDirectusItems composable, for proper types
add getSingletonItem to the useDirectusItems composable, to fetch as Singleton marked collections
=> feat: add typescript generics, add getSingletonItem

docs/content/en/usage/useDirectusAuth.md
New section with an example on how to use a middleware for auth redirect
https://github.com/Intevel/nuxt-directus/issues/8
=> feat: Middleware example to docs

docs/content/en/setup.md, docs/content/en/usage/useDirectusCollections.md, playground/app.vue, src/runtime/composables/useDirectusCollections.ts, src/runtime/types/index.d.ts
Added all the endpoints for manipulating collections as per the [Directus API](https://docs.directus.io/reference/system/collections/)
You can now list, get (by name), update and delete a collection.
Adds a new composable useDirectusCollection.
=> feat(chore): created useCollections composable

README.md, src/runtime/types/index.d.ts
Add the search type to the directus query params. Now we can use search without type errors. Search ist testet and works for items.
=> feat(chore): search type to directus query params

docs/content/en/options.md, src/module.ts, src/runtime/composables/useDirectus.ts
Implemented the authentification option for static tokens, normal token after login have priority!
Will close #31 
And answer the newest discussion #51 
@craigharman @mklueh
=> feat: token authentification

src/module.ts
=> fix(module): autoimport hook deprecated

playground/app.vue, src/runtime/composables/useDirectus.ts
Resolves: #75
adding a throw err so that it can be used by the others to get the error.data to get the error response needed from Directus to do like error logging and UI error notification to their user
=> feat: throw err on $fetch

docs/content/en/usage/useDirectusAuth.md, docs/content/en/usage/useDirectusCollections.md, docs/content/en/usage/useDirectusFiles.md, docs/content/en/usage/useDirectusItems.md, docs/content/en/usage/useDirectusNotifications.md, src/runtime/composables/useDirectusFiles.ts, src/runtime/types/index.d.ts
First time contributing, hope I do things well enough.
So I was looking for a way to pass custom transformation presets, so I can keep controll on what directus is doing and prevent abuse of it. But in doing so I noticed that nuxt-directus didn't have the key variable set so I've added it.
Once done I noticed that some of the docs links weren't working or pointing to the right direction, so I've fixed the too.
=> feat: ability to pass custom image transformation presets and various docs fixes

docs/content/en/options.md
- [ x ] Bug fix (a non-breaking change which fixes an issue)
- [ x ] New feature (a non-breaking change which adds functionality)
1. Describes different rendering modes, including static site rendering by example.
2. Small typo fix in options.md
- [ x ] I have updated the documentation accordingly.
=> feat: Rendering section added to options.md

src/runtime/types/index.d.ts
Better types support for DirectusUser, DirectusFile, and DirectusFolders
=> feat: add types for DirectusUser, DirectusFile and DirectusFolders

README.md
- Improved the readme to mention `nuxt.config.ts` with correct `defineNuxtConfig()`
- Added the nuxt badge and unify the colors
- Removed the CI badge (already available next to latest commit on GitHub now)
=> chore(readme): small improvements

src/runtime/composables/useDirectus.ts
Small Improved to error managment, for more security.
=> feat: improved error management

src/runtime/composables/useDirectus.ts
Fix inconsistency if try-catch is used; migration from showError to createError.
=> fix: use createError instead of showError

src/runtime/composables/useDirectusItems.ts, src/runtime/types/index.d.ts
Fixes the getItems typescript return type to more appropriately match the request.  Resolves: #145
=> fix: return type for getItems

pnpm-lock.yaml, src/runtime/composables/useDirectus.ts
=> fix: invalid url parsing

docs/content/2.composables/1.useDirectusAuth.md, docs/content/4.Types/8.DirectusInvite.md, src/runtime/composables/useDirectusAuth.ts, src/runtime/types/index.d.ts
Added the invite and accept user endpoints to allow creation and acceptance of user invites.
I also alphabetised the imports in `useDirectusAuth.ts`, but this can be reverted if requested.
Added support for 2x missing features in [Directus User API](https://docs.directus.io/reference/system/users.html#invite-a-new-user) for invite and accept invite features.
No tests added as would require an email address to send token to.
=> feat: added user invite provedure

docs/content/1.getting-started/1.setup.md
After detecting a bug: https://github.com/Intevel/nuxt-directus/issues/160#issue-1753634297, I found the solution by adding the configuration of Directus with Nuxt using runtimeConfig https://github.com/Intevel/nuxt-directus/issues/160#issuecomment-1588152137
=> docs: Adding runtimeConfig

src/runtime/composables/useDirectusAuth.ts
`main` does not exist. Removed, as it seems like a typo.
=> Fixed export `main` in useDirectusAuth.ts

package.json, pnpm-lock.yaml
Title say everything.
There are other potential unbuild configs that could see some improvements, will dig into them once I better understand how nuxt/module-builder works.
=> feat!: devOnly fix unbuild configs

package.json, src/module.ts, src/runtime/types/use-directus.d.ts
[Related](https://github.com/nuxt/module-builder/issues/86#issuecomment-1881081273) understanding of the issue.
=> fix: bundler type scanning and more types fixes

package.json
Support TypeScript `bundler` module resolution
Resolves #244
=> fix: Add types to package.json exports

src/runtime/composables/useDirectusItems.ts
This PR fixes the issue #248 (though only a very tiny change was made).
=> Fixes issue #248

src/runtime/composables/useDirectusFiles.ts
This commit adds the ability to upload and delete files in the useDirectusFiles composable. The new functions, uploadFiles and deleteFiles, allow users to upload single or multiple files and delete files by their ID.
This commit adds file upload and deletion capabilities to the `useDirectusFiles` composable. The newly added functions are:
- `uploadFiles`: Supports single or multiple file uploads. Additional metadata like title and tags can be added for files.
- Single file upload: `uploadFiles(file)`
- Multiple file upload: `uploadFiles([file1, file2])`
- Upload with metadata: `uploadFiles(file, { title: 'File Name', tags: ['tag1'] })`
- `deleteFiles`: Supports single or multiple file deletion by ID.
- Single file deletion: `deleteFiles('file-id')`
- Multiple file deletion: …
=> Add file upload and deletion functionality
