- docs/content/en/usage/useDirectusFiles.md
- playground/app.vue
- src/runtime/composables/useDirectusFiles.ts
- src/runtime/types/index.d.ts
add getThumbnail method, to generate image url with given options from the Directus file API
> feat: add getThumbnail method

- src/runtime/composables/useDirectusItems.ts
When we query a single item, we can add a deep parameter to embed many-to-many relations. So, this param should be stringifyied. Applying the same operation to filter is more coherent, regarding the other functions.
If a developer use this feature and already do a JSON.stringify upper, it could add escaping backslashs to the string.
> fix: stringify "deep" key on get item by id

- docs/content/en/usage/useDirectusFiles.md
Fixed a small mistake in the docs:
"getThumbnail" is defined in "useDirectusFiles" not "useDirectus"
> fix(docs): correct usage of getThumbnail

- src/runtime/composables/useDirectusFiles.ts
This adds the `access_token` query param to the url generated by the `getThumbnail` function, using the directus JWT if the user is logged in or the static token if set in the config.
This allows the URL generated to be used in an `<img>` tag directly, even if files are not publicly accessible and require the token for authentication.
> feat: add token to getThumbnail url query params

- docs/content/en/usage/useDirectusUsers.md
- package-lock.json
- playground/app.vue
- playground/nuxt.config.ts
- src/runtime/composables/useDirectusFiles.ts
- src/runtime/composables/useDirectusUsers.ts
- src/runtime/types/index.d.ts
- yarn.lock
- [ x ] New feature (a non-breaking change which adds functionality)
In the existing `useDirectusItems` composable, the `users` collection is not available due to hardcoded URL segment, `/items` in each request.  In the examples, an `Articles` collection is available with an 'author' attribute, but you're unable to get the author's details with the existing composables.  This update adds `useDirectusUsers` composable to allow access to the `/users` area in the exact same manner as `useDirectusItems`.  The code is copied from `useDirectusItems` and modified to match the request and response patterns of the `users` endpoint.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ x ] I have added tests to cover my changes (if not …
> feat: useDirectusUsers composables to access built-in Users collection

- src/module.ts
- src/runtime/composables/useDirectus.ts
- src/runtime/composables/useDirectusAuth.ts
- src/runtime/composables/useDirectusFiles.ts
- src/runtime/composables/useDirectusUrl.ts
- src/runtime/plugin.ts
Adapted the Directus Nuxt module to work with Nuxt 3.4's updated runtime configuration handling, following the deprecation of old (pre-rc) runtimeConfig.
For more information, check out https://github.com/nuxt/nuxt/pull/20082.
This PR adapts the Directus Nuxt module to work with Nuxt 3.4's updated runtime configuration handling. This is necessary due to the deprecation of old (pre-rc) runtimeConfig. The changes ensure that the module continues to work as expected with the latest version of Nuxt.
For more information, please see https://github.com/nuxt/nuxt/pull/20082.
Closes #126.
> Adapt Directus module for Nuxt 3.4 runtime config changes

- src/runtime/types/index.d.ts
Directus [v9.25.0](https://github.com/directus/directus/releases/tag/v9.25.0) added support for `AVIF` image format (https://github.com/directus/directus/pull/17303). `'avif'` is now a supported type in `getThumbnail()`
> feat: add Avif type support to DirectusThumbnailFormat

- pnpm-lock.yaml
- src/runtime/composables/useDirectus.ts
Fixes #147 the error message is now available at the `data` key of the error object. The statusMessage is now the statusText from the response again.
> Fix error handling

- src/runtime/composables/useDirectusAuth.ts
> fix: 'token_expired' always 'true'. #157

- docs/content/1.getting-started/2.options.md
- docs/content/2.composables/1.useDirectusAuth.md
- docs/content/5.examples/1.useAsyncData.md
- docs/content/5.examples/2.redirectUserLogin.md
- docs/content/5.examples/_dir.yml
Update the documentation for version 5.4.0 (rfc#136) + #149.
> docs: Update 5.4.0

- docs/content/2.composables/3.useDirectusToken.md
I found some careless mistakes in the documentation of usedirectustoken (double occurrence of 'refreshToken' as well as incorrect content of 'token') and also noticed that the calls to 'token' and 'expires' were treated as functions when they are not. Therefore, I have changed them to 'token.value' and 'expires.value'.
Additionally, I took the liberty of rearranging the sections as I found them irrelevant. 😉
closes #176
> docs: fix usedirectustoken

- docs/content/1.getting-started/2.options.md
- docs/content/4.Types/8.DirectusInvite.md
- playground/nuxt.config.ts
- src/module.ts
- src/runtime/composables/useDirectusAuth.ts
- src/runtime/composables/useDirectusToken.ts
- src/runtime/plugin.ts
- tsconfig.json
I was trying to get acceptInvite, and inviteUsers functions to work, so:
1. I needed to install with `pnpm add github:Intevel/nuxt-directus`. This is when I got the error that tsconfig.json `extends` does not exist. Fixed by having the minimal required config instead. 
> File ./playground/.nuxt/tsconfig.json does not exists.
2. Fixed a typo: : inviteAccept renamed to acceptInvite.
> Fixed ability to install from Github + Fixed typo

- docs/content/1.getting-started/2.options.md
- src/module.ts
Fixes #181 
The default value for `cookieMaxAge` was in seconds instead of milliseconds as stated in the doc.
> fix: wrong default cookieMaxAge

- docs/content/1.getting-started/2.options.md
- src/module.ts
Didn't open an Issue for this, but basically since the changes in #127 the default value for `directus.url` hasn't been updated to follow the naming convention of the [public `runtimeConfig` env variables](https://nuxt.com/docs/api/configuration/nuxt-config#runtimeconfig)
Quoting the docs:
> Anything under `public` and `app` will be exposed to the frontend as well. Values are automatically replaced by matching env variables at runtime, e.g. setting an environment variable `NUXT_API_KEY=my-api-key` `NUXT_PUBLIC_BASE_URL=/foo/` would overwrite the two values in the example below.
>Example:
>```ts
>  export default {
>    runtimeConfig: {
>      apiKey: '' // Default to an empty string, automatically set at runtime using process.env.NUXT_API_KEY
>      public: {
>        baseURL: '' // …
```
> fix: nuxt env naming convention for directus url

- src/runtime/composables/useDirectusFiles.ts
- src/runtime/composables/useDirectusUrl.ts
In the original code, concatenating directusUrl with the path to the asset using the ${directusUrl}assets/${fileId}. In the updated code, format the URL by using ${directusUrl}/assets/${fileId}, ensuring that there is a forward slash (/) between directusUrl and assets, which will fix the invalid URL issue.
The original code simply returned the directus.url from the config.public object. I am applying a regular expression to remove a trailing slash (/) from the URL. This change ensures that the URL does not end with a slash, which can help prevent issues related to URL formatting and consistency.
The problem these changes solve is an "invalid URL issue on files." By making these adjustments, ensuring that the URLs used for assets are correctly formatted, can prevent errors or unexpected …
> Fix invalid url issue

- src/runtime/types/use-directus-items.d.ts
Fix the type of the result in the items sections, specially in readItems
Before:
After:
> Fix inference of result types

- playground/nuxt.config.ts
- src/runtime/composables/use-directus-auth.ts
- src/runtime/composables/use-directus-tokens.ts
- src/runtime/plugins/auto-refresh.ts
This changes affects:
- `auto-refresh` implementation
- fixes to `useDirectusAuth` and `useDirectusTokens`
Since I managed to fix all issues (known to me) in regard `login` and `refreshTokens` functions (making sure no information were leaked and promises were respected) I wanted to fix the page _flash_ that happens when the DOM should be updated by the currently authenticated user's information.
> [!NOTE]
> To my knowledge the page _flash_ happens because the browser is able to render the DOM before fully mounting vue's logic.
The following is the sequence of operations while using the default module's options in the event of a user was authenticated in a prior session and still has a valid `refresh_token` in their cookies:
```mermaid
sequenceDiagram
participant Client
participant Server …
```
> feat: auth and user state refresh during server to client connection

- src/runtime/plugin.ts
This is a very early PR to make this module compatible with [changes we expect to release in Nuxt v5](https://github.com/nuxt/nuxt/issues/25323).
In [Nuxt v3.7.0](https://github.com/nuxt/nuxt/releases/tag/v3.7.0) we added support for `import.meta.*` (see [original PR](https://github.com/nuxt/nuxt/pull/22428)) and we've been gradually updating docs and moving across from the old `process.*` patterned variables.
As I'm sure you're aware, these variables are replaced at build-time and enable tree-shaking in bundled code.
This change affects _runtime_ code (that is, that is processed by the Nuxt bundler, like vite or webpack) rather than code running in Node. So it really doesn't matter what the string is, but it makes more sense in an ESM-world to use `import.meta` rather than `process`.
(It …
> fix: opt in to `import.meta.*` properties

- README.md
- docs/content/1.getting-started/1.setup.md
This updates the documentation to use the [`nuxi module add` command](https://github.com/nuxt/cli/pull/197) which should simplify docs a bit and also improve user experience as there's no need to add to `nuxt.config` manually.
It's documented [here](https://nuxt.com/docs/api/commands/module#nuxi-module-add).
I may have missed a few spots in the documentation as I'm doing this across the modules ecosystem assisted by the power of regular expressions ✨, so I'd appreciate a review 🙏
> docs: use new `nuxi module add` command in installation

- src/runtime/composables/useDirectusItems.ts
- src/runtime/types/index.d.ts
This pull request introduces a minor but significant change to the `createItems` and `updateItems` functions. 
Previously, these functions did not include the `params: data.params` line, which could potentially limit their functionality and flexibility. By including this line, we allow for additional parameters to be passed into these functions, enhancing their versatility and adaptability to various use cases.
Here are the changes made:
```typescript
// In createItems function
createItems(data) {
// ...existing code...
params: data.params
// ...existing code...
}
// In updateItems function
updateItems(data) {
// ...existing code...
params: data.params
// ...existing code...
}
```
#257
> Add params in useDirectusItems.ts (updateItem&createItems)

- src/module.ts
Export the package's runtime types instead of only the module's configuration types in the package's `exports` field.
With this I want to get back to https://github.com/Intevel/nuxt-directus/issues/244, which isn't quite fixed yet. Currently the package only exports the `ModuleOptions` types. Hence with moduleResolution type `bundler` (introduced with the latest [Nuxt versions](https://nuxt.com/docs/guide/going-further/features#typescriptbundlerresolution)), it is not possible to e.g. `import type { DirectusFile } from 'nuxt-directus'` without type errors. This change ensures to export the runtime types instead of only the module's configuration types.
Tested on a local Nuxt v3.12.2 with `typescriptBundlerResolution: true`.
> fix: update package exports types
